[
    { trigger: "([a-zA-Z])hat", replacement: "\\hat{[[0]]}", options: "rmA" },
    { trigger: "([a-zA-Z])bar", replacement: "\\bar{[[0]]}", options: "rmA" },
    { trigger: "([a-zA-Z])dot", replacement: "\\dot{[[0]]}", options: "rmA", priority: -1 },
    { trigger: "([a-zA-Z])ddot", replacement: "\\ddot{[[0]]}", options: "rmA", priority: 1 },
    { trigger: "([a-zA-Z])tilde", replacement: "\\tilde{[[0]]}", options: "rmA" },
    { trigger: "([a-zA-Z])und", replacement: "\\underline{[[0]]}", options: "rmA" },
    { trigger: "([a-zA-Z])vec", replacement: "\\vec{[[0]]}", options: "rmA" },
    { trigger: "([a-zA-Z]),\\.", replacement: "\\mathbf{[[0]]}", options: "rmA" },
    { trigger: "([a-zA-Z])\\.,", replacement: "\\mathbf{[[0]]}", options: "rmA" },
    { trigger: "\\\\(${GREEK}),\\.", replacement: "\\boldsymbol{\\[[0]]}", options: "rmA" },
    { trigger: "\\\\(${GREEK})\\.,", replacement: "\\boldsymbol{\\[[0]]}", options: "rmA" },

    { trigger: "hat", replacement: "\\hat{$0}$1", options: "mA" },
    { trigger: "bar", replacement: "\\bar{$0}$1", options: "mA" },
    { trigger: "dot", replacement: "\\dot{$0}$1", options: "mA", priority: -1 },
    { trigger: "ddot", replacement: "\\ddot{$0}$1", options: "mA" },
    { trigger: "cdot", replacement: "\\cdot", options: "mA" },
    { trigger: "vdot", replacement: "\\vdot", options: "rmA", priority: 1 },
    { trigger: "tilde", replacement: "\\tilde{$0}$1", options: "mA" },
    { trigger: "und", replacement: "\\underline{$0}$1", options: "mA" },
    { trigger: "vec", replacement: "\\vec{$0}$1", options: "mA" },

    { trigger: "bf", replacement: "\\mathbf{$0}", options: "mA" },
    { trigger: "rm", replacement: "\\mathrm{$0}$1", options: "mA" },
]