[
    { trigger: "ooo", replacement: "\\infty", options: "mA" },
    { trigger: "sum", replacement: "\\sum", options: "mA" },
    { trigger: "prod", replacement: "\\prod", options: "mA" },
    { trigger: "\\sum", replacement: "\\sum_{${0:i}=${1:1}}^{${2:N}} $3", options: "m" },
    { trigger: "\\prod", replacement: "\\prod_{${0:i}=${1:1}}^{${2:N}} $3", options: "m" },
    { trigger: "lim", replacement: "\\lim_{ ${0:n} \\to ${1:\\infty} } $2", options: "mA" },
    { trigger: "+-", replacement: "\\pm", options: "mA" },
    { trigger: "-+", replacement: "\\mp", options: "mA" },
    { trigger: "...", replacement: "\\dots", options: "mA" },
    { trigger: "nabl", replacement: "\\nabla", options: "mA" },
    { trigger: "grad", replacement: "\\grad", options: "mA" },
    { trigger: "del", replacement: "\\nabla", options: "mA" },
    { trigger: "xx", replacement: "\\times", options: "mA" },
    { trigger: "**", replacement: "\\cdot", options: "mA" },
    { trigger: "para", replacement: "\\parallel", options: "mA" },

    { trigger: "===", replacement: "\\equiv", options: "mA" },
    { trigger: "!=", replacement: "\\neq", options: "mA" },
    { trigger: ">=", replacement: "\\geq", options: "mA" },
    { trigger: "<=", replacement: "\\leq", options: "mA" },
    { trigger: ">>", replacement: "\\gg", options: "mA" },
    { trigger: "<<", replacement: "\\ll", options: "mA" },
    { trigger: "simm", replacement: "\\sim", options: "mA" },
    { trigger: "sim=", replacement: "\\simeq", options: "mA" },
    { trigger: "prop", replacement: "\\propto", options: "mA" },
]